'use client'
import Link from 'next/link'
import {useState} from 'react'
import {forgotPassword,resetPassword,logout} from '../../lib/api'
export default function ForgotPassword(){
 const [email,setEmail]=useState(''),[code,setCode]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[done,setDone]=useState(false)
 async function send(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await forgotPassword(email);setMessage(r.message);setSent(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function reset(e:React.FormEvent){e.preventDefault();if(password!==confirm){setError('Passwords do not match.');return}setBusy(true);setError('');try{await resetPassword(email,code,password);logout();setPassword('');setConfirm('');setCode('');setDone(true);setMessage('Password updated. Sign in with your new password.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <main className="signupWrap"><section className="signupCard"><h1>Reset password</h1>{!done&&<><form onSubmit={send}><label>Email<div className="field"><input type="email" required value={email} onChange={e=>{setEmail(e.target.value);setSent(false)}}/></div></label><button className="primary" disabled={busy}>Send reset code</button></form>{sent&&<form onSubmit={reset}><label>Reset code<div className="field"><input required pattern="[0-9]{6}" inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))}/></div></label><label>New password<div className="field"><input type="password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/></div></label><label>Confirm password<div className="field"><input type="password" required minLength={8} value={confirm} onChange={e=>setConfirm(e.target.value)}/></div></label><button className="primary" disabled={busy}>Update password</button></form>}</>}{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="formError">{error}</p>}<Link href="/login">Return to login</Link></section></main>
}
